### ISSUE TITLE
Mixups between Azure and AWS in walkthrough of Scenario 2

### ISSUE THREAD

**Issue by fc7** [RedHat-Middleware-Workshops/service-interconnect-lab-instructions#1] opened 2023-08-25 12:14 UTC
I ran the demo today and would like to report two related minor issues in Scenario 2:

1. The screenshot accompanying step 1 of ”Initialize Red Hat Service Interconnect in the Azure cluster” is incorrect.
https://github.com/RedHat-Middleware-Workshops/service-interconnect-lab-instructions/blob/main/walkthroughs/skupper-gateway/walkthrough.adoc?plain=1#L448
It should be `azure_terminal_icon.png` instead, not `aws_terminal_icon.png`.
2. In Step 4 further down, replace “aws terminal” by “azure terminal” and “aws namespace” by “azure namespace”, respectively.
https://github.com/RedHat-Middleware-Workshops/service-interconnect-lab-instructions/blob/main/walkthroughs/skupper-gateway/walkthrough.adoc?plain=1#L466

**Comment by rpscodes** [comment] 2023-09-03 16:03
Thank you so much @fc7 for pointing this out. The issue is now fixed in the latest commit. cc: @markusjnagel .

**Closed as completed by rpscodes** 2023-09-03 16:03 UTC
